export default [
  {
    path: "/es",
    name: "Inicio",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name: "Inicio",
      component: () => import("pages/IndexPage.vue") }],
  },
  {
    path: '/es/informazioni',
    name: 'Informazioni',
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name: "Informazioni",
      component: () => import("src/pages/About.vue") }],
  },
  {
    path: '/es/api',
    name: 'api-es',
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"api-es",
      component: () => import("src/pages/API.vue") }],
  },
  {
    path: '/es/servicios',
    name: 'Servicios',
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Servicios",
      component: () => import("pages/Services.vue") }],
  },
  {
    path: '/es/base-de-conocimientos',
    name: 'base-de-conocimientos',
    props: true,
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Base de conocimientos",
      component: () => import("src/pages/blog/Index.vue") }],
  },
  {
    path: '/es/base-de-conocimientos/:category',
    name: 'Categoría',
    props: true,
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Categoría",
      component: () => import("src/pages/blog/Category.vue") }],
  },
  {
    path: '/es/base-de-conocimientos/:category/:slug',
    name: 'Mostrar',
    props: true,
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Mostrar",
      component: () => import("src/pages/blog/Show.vue") }],
  },
  {
    path: '/es/preguntas-frecuentes',
    name: 'Preguntas frecuentes',
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Preguntas-frecuentes",
      component: () => import("src/pages/FAQs.vue") }],
  },
  {
    path: "/es/validacion-de-patentes-europeas-en-turquia",
    name: "Validación de patentes europeas en Turquía",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Validación de patentes europeas en Turquía",
      component: () => import("src/pages/services/EPValidationPage.vue") }],
  },
  {
    path: "/es/entrada-en-la-fase-nacional-del-pct-en-turquia",
    name: "Entrada en la fase nacional del PCT en Turquía",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Entrada en la fase nacional del PCT en Turquía",
      component: () => import("src/pages/services/PCTEntryPage.vue") }],
  },
  {
    path: "/es/renovacion-de-patentes-en-Turquia",
    name: "Renovación de patentes en Turquía",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Renovación de patentes en Turquía",
      component: () => import("src/pages/services/PatentAnnuityPage.vue") }],
  },
  {
    path: "/es/contacto",
    name: "Contacto",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Contacto",
      component: () => import("pages/ContactPage.vue") }],
  },
  {
    path: "/es/Ordenar/:slug",
    name: "Ordenar",
    component: () => import("layouts/MainLayout.vue"),
    children: [{ path: "",
      name:"Ordenar",
      component: () => import("pages/Orders.vue") }],
  },

]
