<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('knowledge_base', function (Blueprint $table) {



            $knowledge_base = array(
                //tr
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme",'slug' => 'turkiye-de-avrupa-patent-gecerlendirme','question' => "Avrupa patentini Türkiye'de geçerlendirmek mümkün mü?",'question_link' => 'turkiye-de-avrupa-patent-gecerlendirme-mumkun-mu','answer' => "Evet, Türkiye Avrupa Patent Sözleşmesi'ne taraf bir devlettir ve geçerlendirme, EPO tarafından verildikten sonra Avrupa patentine ilişkin Türkiye'de uygulanabilir bir hakkın sahibi olmak için zorunlu bir adımdır. Ayrıca, Avrupa patent geçerlendirmeleri Türkiye'de oldukça yaygındır, bu nedenle Türkiye'de bir yılda verilen patentlerin yaklaşık üçte biri Avrupa patent geçerlendirmeleridir.",'type' => 'Knowledge Base','created_at' => NULL,'updated_at' => NULL),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => "Türkiye'de Avrupa patent geçerlendirmeleri için bir ulusal profesyonel temsilci atanması zorunlu mudur?", 'question_link' => 'turkiye-de-avrupa-patent-gecerlendirme-icin-temsilci-zorunlu-mudur', 'answer' => 'Evet, başvuru sahibinin Türkiye\'de bir ikametgahı veya merkezi yoksa, Türkiye\'de Avrupa patent geçerlendirmeleri için kayıtlı bir Türk patent vekili atamanız gerekmektedir. Ayrıca, ikamet ve/veya iş yeri gerekliliklerini karşılıyor olsanız bile, patent dairesi ile daha iyi iletişim olanakları nedeniyle hala ulusal bir patent vekiliyle çalışmanızı tavsiye ederiz.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme",'slug' => "turkiye-de-avrupa-patent-gecerlendirme",'question' => "Türkiye, Londra Anlaşması'na taraf bir devlet midir?",'question_link' => 'turkiye-londra-anlasmasina-taraf-devlet-midir','answer' => "Hayır, Türkiye Londra Anlaşması'na taraf bir devlet değildir. Bu nedenle, tam patent açıklamasının Türkçeye çevrilmesi gerekmektedir.",'type' => 'Knowledge Base','created_at' => NULL,'updated_at' => NULL),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => "turkiye-de-avrupa-patent-gecerlendirme", 'question' => 'Avrupa patent geçerlendirmelerinde açıklama çevirisi gerekli midir?', 'question_link' => 'turkiye-de-avrupa-patent-gecerlendirmelerinde-aciklama-cevirisi-gerekli-midir', 'answer' => 'Evet. Turkpatent, talep edilen patent özelliklerinin tamamının, yani iddiaların, çizimlerin ve açıklamanın Türkçe\'ye çevrilmesini gerektirmektedir. Validasyonunuzda ortaya çıkacak son çeviri ücretleri hakkında hızlı bir fiyat teklifi almak için <a href="/turkiye-de-avrupa-patent-gecerlendirme">EP Validasyon aracımızı</a> kullanabilirsiniz.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Avrupa patent geçerlendirmesinin çevirisinin dosyalanması için süre nedir?', 'question_link' => 'turkiye-de-avrupa-patent-gecerlendirmesinin-cevirisinin-dosyalanmasi-icin-sure-nedir', 'answer' => 'Çevirinin, Avrupa Patent Bülteni\'nde yayınlanan verili tarihten itibaren üç ay içinde dosyalanması gerekmektedir. Bir süre uzatımı için ücret ödenerek üç aylık bir süre daha mümkündür.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Avrupa patentinin geç geçerlendirmesi mümkün müdür?', 'question_link' => 'turkiye-de-avrupa-patentinin-gec-gecerlendirmesi-mumkun-mudur', 'answer' => 'Ücret ödenerek üç aylık bir süre uzatımı mevcuttur. Ancak, bu üç aylık süre zarfında çevirinin dosyalanma seçeneği, başvurunun belirtilen yayınlama tarihinden itibaren ilk üç aylık süre içinde önceden ücret ve ek ücretin ödenmiş olması durumunda mümkündür. Eğer durumunuz bu koşulları karşılamıyorsa, patentinizi geçerlendirmek hala mümkün olabilecek bazı özel durumlar olabilir. Bu konuda daha fazla bilgiye ihtiyacınız varsa, lütfen bize <a href="/contact?=Late-EP-Application">iletişim</a> adresinden başvurun.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Türkiye\'de bir Avrupa patentinin geçerlendirilmesi ne kadar maliyetlidir?', 'question_link' => 'turkiye-de-bir-avrupa-patentinin-gecerlendirilmesi-ne-kadar-maliyetlidir', 'answer' => 'Türkiye\'de Avrupa patentinin geçerlendirilmesi maliyetleri resmi ücretler, temsilci ücretleri ve çeviri ücretlerinden oluşur. Avrupa patentinin geçerlendirme için resmi ücretler her yıl önemli ölçüde değişebilir ve en güncel resmi ücretleri <a href="bilgi-bankasi/turkiye-de-avrupa-patent-gecerlendirme/turkiye-de-avrupa-patent-gecerlendirmeleri-icin-resmi-ucretler-nelerdir">bu sayfada</a> inceleyebilirsiniz. <br> Geçerlendirmenin toplam maliyeti patentten patente değişiklik gösterir. Avrupa patentinizin Türkiye\'deki geçerlendirmesi için anlık ve doğru bir fiyat teklifi almak için EP Validasyon aracımızı kullanabilirsiniz <a href="/turkiye-de-avrupa-patent-gecerlendirme">.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Türkiye\'de Avrupa patent geçerlendirmeleri için resmi ücretler nelerdir?', 'question_link' => 'turkiye-de-avrupa-patent-gecerlendirme-icin-resmi-ucretler-nelerdir', 'answer' => '2023 yılında Avrupa patent çevirisinin yayınlanması için resmi ücret TRY 8910.00\'dir. Ancak, çevirinin geç dosyalanması için üç aylık süre uzatımı talep ediliyorsa, ek ücret olarak TRY 5040.00 önceden ödenmelidir. <br> Avrupa patentinizin Türkiye\'deki geçerlendirilmesi için hem resmi ücretleri hem de toplam maliyetleri doğru bir şekilde hesaplamak için <a href="/turkiye-de-avrupa-patent-gecerlendirme">EP Validasyon aracımızı</a> kullanabilirsiniz.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Türkiye\'de bir Avrupa patentini nasıl geçerlendirebilirim?', 'question_link' => 'turkiye-de-bir-avrupa-patentini-nasil-gecerlendirebilirim', 'answer' => 'Türkiye\'de bir Avrupa patentini geçerlendirmek için aşağıdaki adımları izleyebilirsiniz: <ol> <li>Avrupa Patent Teşkilatı (EPO) tarafından verilen Avrupa patentine başvurunuzu yapın.</li> <li>Avrupa patentinin Türkiye\'de geçerlendirilmesi için başvurunuzda çeviri yapmanız gerekmektedir. Patent çevirisi için kayıtlı bir Türk patent vekili ile çalışmanız önerilir.</li> <li>Çevirinizi, Avrupa Patent Bülteni\'nde yayınlanan tarihten itibaren üç ay içinde Türk Patent ve Marka Kurumu\'na (Turkpatent) dosyalamanız gerekmektedir.</li> <li>Geçerlendirmenin resmi ücretlerini ödeyerek başvurunuzu tamamlayın.</li> </ol> Türkiye\'deki Avrupa patent geçerlendirmesi hakkında daha fazla bilgi almak ve geçerlendirmenin toplam maliyetini hesaplamak için EP Validasyon aracımızı kullanabilirsiniz <a href="/turkiye-de-avrupa-patent-gecerlendirme">.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array('title' => "Türkiye'de Avrupa Patent Geçerlendirme", 'slug' => 'turkiye-de-avrupa-patent-gecerlendirme', 'question' => 'Türkiye\'de Avrupa patent geçerlendirmeleri için kayıtlı bir Türk patent vekiliyle çalışmak zorunlu mudur?', 'question_link' => 'turkiye-de-avrupa-patent-gecerlendirme-icin-turk-patent-vekili-zorunlu-mudur', 'answer' => 'Evet, başvuru sahibinin Türkiye\'de bir ikametgahı veya merkezi yoksa, Türkiye\'de Avrupa patent geçerlendirmeleri için kayıtlı bir Türk patent vekili atamanız gerekmektedir. Ayrıca, ikamet ve/veya iş yeri gerekliliklerini karşılıyor olsanız bile, patent dairesi ile daha iyi iletişim olanakları nedeniyle hala ulusal bir patent vekiliyle çalışmanızı tavsiye ederiz.', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL ),
                array("title" => "Türkiye'de Avrupa Patent Geçerlendirme", "slug" => "turkiye-de-avrupa-patent-gecerlendirme", "question" => "Türkiye'de Avrupa patenti geçerli kılmak için vekaletname gerekiyor mu?", "question_link" => "turkiye-de-avrupa-patenti-gecerli-kilmak-icin-vekaletname-gerekiyor-mu", "answer" => "Hayır, Türkiye'de Avrupa patent validasyonu için vekaletname gerekmemektedir. Ancak avukatınız, gelecekteki gereksinimler için başvuru sahibinden imzalı bir vekaletname talep etmeyi tercih edebilir.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Türkiye'de Avrupa Patent Geçerlendirme", "slug" => "turkiye-de-avrupa-patent-gecerlendirme", "question" => "Çevirinin geç teslim edilmesi mümkün müdür?", "question_link" => "cevirinin-gec-teslim-edilmesi-mumkun-mudur", "answer" => "Evet, bir ücret ödeyerek üç aylık bir süre uzatması yapılabilir. Ancak çevirinin bu üç aylık süre uzatması içinde sunulabilmesi için yayın ücreti ve ek ücretin başlangıç süresi olan ilk üç ay içinde ödenmiş olması gerekmektedir.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Türkiye'de Avrupa Patent Geçerlendirme", "slug" => "turkiye-de-avrupa-patent-gecerlendirme", "question" => "Çevirinin düzeltilmesine izin veriliyor mu?", "question_link" => "cevirinin-duzeltilmesine-izin-veriliyor-mu", "answer" => "Evet, Türkiye'de çevirinin düzeltilmesine izin verilmektedir. Avrupa patentinin geçerlendirilmesinden sonra patentin açıklamasının düzeltilmiş bir çevirisi herhangi bir zamanda sunulabilir. Düzeltme için resmi ücretleri burada inceleyebilirsiniz.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Türkiye'de Avrupa Patent Geçerlendirme", "slug" => "turkiye-de-avrupa-patent-gecerlendirme", "question" => "Düzeltme çevirisi sunulurken ödenen resmi ücretler nelerdir?", "question_link" => "duzeltme-cevirisi-sunulurken-odenmis-resmi-ucretler-nelerdir", "answer" => "Çevirinin düzeltilmesi gerekiyorsa, 2023 yılında patent açıklamasının düzeltilmiş çevirisi için ödenmesi gereken resmi ücret TRY 2820.00'dir.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),

                //es
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Es posible validar una patente europea en Turquía?", "question_link" => "es-posible-validar-una-patente-europea-en-turquia", "answer" => "Sí, Turquía es un estado contratante del Convenio sobre la Patente Europea y la validación es un paso obligatorio para poseer un derecho ejecutable en Turquía en relación con una patente europea después de su concesión ante la OEP. También es común que las validaciones EP sean muy comunes en Turquía, de manera que aproximadamente un tercio de todas las concesiones de patentes en un año en Turquía son validaciones EP.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Es necesario designar a un representante profesional nacional para las validaciones de patentes europeas en Turquía?", "question_link" => "es-necesario-designar-a-un-representante-profesional-nacional-para-las-validaciones-de-patentes-europeas-en-turquia", "answer" => "Sí, si el solicitante no tiene residencia turca ni una sede en Turquía, debe designar a un abogado de patentes turco registrado para las validaciones de patentes europeas en Turquía. Además, incluso si cumple con los requisitos de residencia y/o lugar de negocio, le recomendamos que trabaje con un abogado de patentes nacional debido a las mejores perspectivas de comunicación con la oficina de patentes.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Es Turquía un estado contratante del Acuerdo de Londres?", "question_link" => "es-turquia-un-estado-contratante-del-acuerdo-de-londres", "answer" => "No, Turquía no es un estado contratante del Acuerdo de Londres. Por lo tanto, se requiere una traducción al turco de la especificación completa de la patente.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Se requiere la traducción de la descripción para las validaciones de patentes europeas en Turquía?", "question_link" => "se-requiere-la-traduccion-de-la-descripcion-para-las-validaciones-de-patentes-europeas-en-turquia", "answer" => "Sí. Turkpatent requiere que la especificación completa, incluyendo las reivindicaciones, los dibujos y la descripción, se traduzcan al turco. Puede utilizar nuestra <a href='/validacion-de-patente-europea-en-turquia'>herramienta de Validación EP</a> para obtener un presupuesto rápido sobre las tarifas de traducción finales que se incurrirán en su validación.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuál es el plazo para presentar la traducción de una validación de patente europea en Turquía?", "question_link" => "cual-es-el-plazo-para-presentar-la-traduccion-de-una-validacion-de-patente-europea-en-turquia", "answer" => "Se requiere presentar la traducción dentro de los tres meses posteriores a la fecha en que se publica la mención de la concesión en el Boletín de Patentes Europeas. También es posible una extensión de tres meses pagando un recargo.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Es posible la validación tardía de una patente europea?", "question_link" => "es-posible-la-validacion-tardia-de-una-patente-europea", "answer" => "Es posible una extensión de tres meses para presentar la traducción pagando un recargo. Pero la opción de presentar la traducción durante esta extensión de tres meses solo está disponible si se han pagado anticipadamente la tarifa de publicación y el recargo dentro del período inicial de tres meses desde la mención de la concesión. Si su caso no cumple con estas condiciones, puede haber algunos casos particulares en los que aún sea posible validar su patente. En caso de necesitar más información al respecto, por favor <a href='/contactar?Validacion-EP-Tardia'>contáctenos</a>.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuánto cuesta la validación de una patente europea en Turquía?", "question_link" => "cuanto-cuesta-la-validacion-de-una-patente-europea-en-turquia", "answer" => "Los costos de validación de una patente europea en Turquía incluyen tarifas oficiales, honorarios de representación y tarifas de traducción. Las tarifas oficiales para presentar una validación de patente europea pueden variar significativamente cada año y puede consultar las tarifas oficiales más recientes en <a href='base-de-conocimientos/validacion-de-patente-europea-en-turquia/cuales-son-las-tarifas-oficiales-para-las-validaciones-de-patentes-europeas-en-turquia'>esta página</a>. El costo total de una validación varía de una patente a otra. Puede utilizar nuestra herramienta de Validación EP <a href='/validacion-de-patente-europea-en-turquia'>para obtener un presupuesto preciso instantáneo para la validación de su patente europea en Turquía</a>.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL ),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuáles son las tasas oficiales para la validación de patentes europeas en Turquía?", "question_link" => "cuales-son-las-tasas-oficiales-para-la-validacion-de-patentes-europeas-en-turquia", "answer" => "La tasa oficial es de TRY 8910,00 en 2023 para la publicación de una traducción de la especificación de la patente. Pero para una prórroga de tres meses para la presentación tardía de la traducción, se requiere el pago anticipado de un recargo de TRY 5040,00. <br> Puedes utilizar nuestra <a href='/validacion-de-patente-europea-en-turquia'>herramienta de validación EP</a> para obtener un cálculo preciso tanto de las tasas oficiales como de los costos totales para la validación de tus patentes europeas en Turquía.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuándo vencen las tasas oficiales?", "question_link" => "cuando-vencen-las-tasas-oficiales", "answer" => "Las tasas oficiales vencen dentro de los tres meses posteriores a la fecha en que se publica la mención de la concesión en el Boletín de Patentes Europeas. Si solicitas una prórroga de tres meses por presentación tardía, el recargo debe pagarse por adelantado dentro del mismo período.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuánto tiempo lleva validar una patente europea en Turquía?", "question_link" => "cuanto-tiempo-lleva-validar-una-patente-europea-en-turquia", "answer" => "La validación de una patente europea en Turquía generalmente se completa en pocos días. Sin embargo, el proceso de traducción tiene cierta variabilidad natural incorporada. Para estar en el lado seguro y no incurrir en cargos adicionales, se recomiendan instrucciones oportunas.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Se requiere un poder notarial para validar una patente europea en Turquía?", "question_link" => "se-requiere-un-poder-notarial-para-validar-una-patente-europea-en-turquia", "answer" => "No, no se requiere un poder notarial en Turquía para la validación de patentes europeas. Sin embargo, tu abogado aún puede preferir contar con un poder notarial ejecutado por el solicitante en caso de futuros requisitos.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Es posible presentar la traducción tarde?", "question_link" => "es-posible-presentar-la-traduccion-tarde", "answer" => "Sí, está disponible una prórroga de tres meses pagando un recargo. Pero la opción de presentar la traducción durante esta prórroga de tres meses solo está disponible si se han pagado la tasa de publicación y el recargo <b>anticipadamente</b>, dentro del período inicial de tres meses desde la mención de la concesión.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Se permite la corrección de la traducción?", "question_link" => "se-permite-la-correccion-de-la-traduccion", "answer" => "Sí, se permiten las correcciones de traducción en Turquía. Una traducción corregida de la especificación de la patente se puede presentar en cualquier momento después de la validación de la patente europea. Puedes revisar las tasas oficiales más recientes para presentar una traducción corregida aquí <a href='/base-de-conocimientos/validacion-de-patente-europea-en-turquia/se-requiere-un-poder-notarial-para-validar-una-patente-europea-en-turquia'></a>.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validación de Patente Europea en Turquía", "slug" => "validacion-de-patente-europea-en-turquia", "question" => "¿Cuáles son las tasas oficiales a pagar al presentar una traducción corregida?", "question_link" => "cuales-son-las-tasas-oficiales-a-pagar-al-presentar-una-traduccion-corregida", "answer" => "Si necesitas una corrección de traducción, la tasa oficial para la publicación de una traducción corregida de la especificación de la patente es de TRY 2820,00 durante el año 2023.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),

                //it
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'È possibile convalidare un brevetto europeo in Turchia?', 'question_link' => 'e-possibile-convalidare-un-brevetto-europeo-in-turchia', 'answer' => "Sì, la Turchia è uno Stato contraente della Convenzione europea sul brevetto e la convalida è un passaggio obbligatorio per ottenere un diritto esecutivo in Turchia relativamente a un brevetto europeo dopo il rilascio da parte dell'EPO. È anche frequente la convalida di brevetti europei in Turchia, tanto che circa un terzo di tutti i brevetti rilasciati in Turchia in un anno sono convalidazioni di brevetti europei.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'È necessario nominare un rappresentante professionale nazionale per la convalida di brevetti europei in Turchia?', 'question_link' => 'e-necessario-nominare-un-rappresentante-professionale-nazionale-per-la-convalida-di-brevetti-europei-in-turchia', 'answer' => "Sì, se il richiedente non ha una residenza turca o una sede legale situata in Turchia, è necessario nominare un avvocato brevettuale turco registrato per la convalida di brevetti europei in Turchia. Inoltre, anche se si soddisfano i requisiti di residenza e/o di sede legale, consigliamo comunque di lavorare con un avvocato brevettuale nazionale per una migliore comunicazione con l'ufficio brevetti.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => "La Turchia è uno Stato contraente dell'Accordo di Londra?", 'question_link' => 'la-turchia-e-uno-stato-contraente-dell-accordo-di-londra', 'answer' => "No, la Turchia non è uno Stato contraente dell'Accordo di Londra. Pertanto, è richiesta una traduzione in turco della descrizione completa del brevetto.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'È necessaria la traduzione della descrizione per la convalida di brevetti europei in Turchia?', 'question_link' => 'e-necessaria-la-traduzione-della-descrizione-per-la-convalida-di-brevetti-europei-in-turchia', 'answer' => "Sì. Turkpatent richiede che l'intera specifica, comprese le rivendicazioni, i disegni e la descrizione, venga tradotta in turco. Puoi utilizzare il nostro <a href='/validazione-brevetto-europeo-in-turchia'>strumento di convalida EP</a> per ottenere un preventivo rapido sulle spese di traduzione finali da sostenere per la tua convalida.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'Qual è il periodo per presentare la traduzione di una convalida di brevetto europeo in Turchia?', 'question_link' => 'qual-e-il-periodo-per-presentare-la-traduzione-di-una-convalida-di-brevetto-europeo-in-turchia', 'answer' => "La traduzione deve essere presentata entro tre mesi dalla data di pubblicazione della menzione del rilascio nel Bollettino europeo dei brevetti. È possibile ottenere un'estensione di tre mesi pagando un sovrapprezzo.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'È possibile effettuare una convalida tardiva di un brevetto europeo?', 'question_link' => 'e-possibile-effettuare-una-convalida-tardiva-di-un-brevetto-europeo', 'answer' => "È possibile ottenere un'estensione di tre mesi per presentare la traduzione pagando un sovrapprezzo. Tuttavia, l'opzione di presentare la traduzione durante questa estensione di tre mesi è disponibile solo se la tassa di pubblicazione e il sovrapprezzo sono stati pagati <b>in anticipo</b>, entro il periodo iniziale di tre mesi dalla menzione del rilascio. Se il tuo caso non soddisfa queste condizioni, potrebbero esserci alcuni casi particolari in cui è ancora possibile convalidare il tuo brevetto. Se hai bisogno di ulteriori informazioni in merito, ti preghiamo di <a href='/contatto?=convalida-EP-tardiva'>contattarci</a>.", 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validazione brevetto europeo in Turchia', 'slug' => 'validazione-brevetto-europeo-in-turchia', 'question' => 'Quanto costa la convalida di un brevetto europeo in Turchia?', 'question_link' => 'quanto-costa-la-convalida-di-un-brevetto-europeo-in-turchia', 'answer' => 'I costi di convalida di un brevetto europeo in Turchia includono le tasse ufficiali, le tariffe dei rappresentanti e le spese di traduzione. Le tasse ufficiali per la presentazione di una convalida di brevetto europeo possono variare notevolmente ogni anno e puoi consultare le tasse ufficiali più recenti in <a href="knowledge-base/validazione-brevetto-europeo-in-turchia/quali-sono-le-tasse-ufficiali-per-la-convalida-di-brevetti-europei-in-turchia">questa pagina</a>. <br> Il costo totale di una convalida varia da brevetto a brevetto. Puoi utilizzare il nostro strumento di convalida EP <a href="/validazione-brevetto-europeo-in-turchia">per ottenere un preventivo istantaneo e preciso per la convalida del tuo brevetto europeo in Turchia.</a>', 'type' => 'Knowledge Base', 'created_at' => NULL, 'updated_at' => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "Quali sono le tariffe ufficiali per la convalida di brevetti europei in Turchia?", "question_link" => "quali-sono-le-tariffe-ufficiali-per-la-convalida-di-brevetti-europei-in-turchia", "answer" => "La tariffa ufficiale è di TRY 8910,00 nel 2023 per la pubblicazione di una traduzione della specifica del brevetto. Ma per una proroga di tre mesi per la presentazione tardiva della traduzione è richiesto il pagamento anticipato di un sovrapprezzo di TRY 5040,00. <br> Puoi utilizzare il nostro <a href='/validazione-brevetto-europeo-in-turchia'>strumento di convalida EP</a> per ottenere un calcolo preciso delle tariffe ufficiali e dei costi totali per la convalida dei tuoi brevetti europei in Turchia.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "Entro quando devono essere pagate le tariffe ufficiali?", "question_link" => "entro-quando-devono-essere-pagate-le-tariffe-ufficiali", "answer" => "Le tariffe ufficiali devono essere pagate entro tre mesi dalla data di pubblicazione della menzione del rilascio nel Bollettino dei brevetti europei. Se richiedi una proroga di tre mesi per la presentazione tardiva, il sovrapprezzo deve essere pagato anticipatamente nello stesso periodo.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "Quanto tempo ci vuole per convalidare un brevetto europeo in Turchia?", "question_link" => "quanto-tempo-ci-vuole-per-convalidare-un-brevetto-europeo-in-turchia", "answer" => "Di solito, la convalida di un brevetto europeo in Turchia viene completata entro pochi giorni. Tuttavia, il processo di traduzione ha una certa variabilità naturale. Per evitare sovrapprezzi aggiuntivi, si consiglia di inviare le istruzioni in tempo utile.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "È necessaria una procura per convalidare un brevetto europeo in Turchia?", "question_link" => "e-necessaria-una-procura-per-convalidare-un-brevetto-europeo-in-turchia", "answer" => "No, in Turchia non è richiesta una procura per la convalida di brevetti europei. Tuttavia, il tuo consulente potrebbe preferire di avere una procura eseguita da parte del richiedente in previsione di eventuali future necessità.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "È possibile presentare la traduzione in ritardo?", "question_link" => "e-possibile-presentare-la-traduzione-in-ritardo", "answer" => "Sì, è possibile ottenere una proroga di tre mesi pagando un sovrapprezzo. Tuttavia, l'opzione di presentare la traduzione durante questa proroga di tre mesi è disponibile solo se la tassa di pubblicazione e il sovrapprezzo sono stati pagati <b>anticipatamente</b>, entro il periodo iniziale di tre mesi dalla menzione del rilascio.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "È consentita la correzione della traduzione?", "question_link" => "e-consentita-la-correzione-della-traduzione", "answer" => "Sì, è consentita la correzione delle traduzioni in Turchia. Una traduzione corretta della specifica del brevetto può essere presentata in qualsiasi momento dopo la convalida del brevetto europeo. Puoi consultare le tariffe ufficiali più recenti per la presentazione di una traduzione corretta qui <a href='knowledge-base/validazione-brevetto-europeo-in-turchia/e-necessaria-una-procura-per-convalidare-un-brevetto-europeo-in-turchia'></a>.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validazione brevetto europeo in Turchia", "slug" => "validazione-brevetto-europeo-in-turchia", "question" => "Quali sono le tariffe ufficiali da pagare per la presentazione di una traduzione corretta?", "question_link" => "quali-sono-le-tariffe-ufficiali-da-pagare-per-la-presentazione-di-una-traduzione-corretta", "answer" => "Se hai bisogno di una correzione della traduzione, la tariffa ufficiale per la pubblicazione di una traduzione corretta della specifica del brevetto è di TRY 2820,00 durante l'anno 2023.", "type" => "Knowledge Base", "created_at" => NULL, "updated_at" => NULL),

                //fr
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "Est-il possible de valider un brevet européen en Turquie ?", "question_link" => "est-il-possible-de-valider-un-brevet-europeen-en-turquie", "answer" => "Oui, la Turquie est un État contractant à la Convention sur le brevet européen et la validation est une étape obligatoire pour obtenir un droit exécutoire en Turquie concernant un brevet européen après la délivrance par l'OEB. Il est également courant que les validations EP soient effectuées en Turquie, environ un tiers de toutes les délivrances de brevets en Turquie chaque année étant des validations EP.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "Faut-il nommer un représentant professionnel national pour les validations de brevets européens en Turquie ?", "question_link" => "faut-il-nommer-un-representant-professionnel-national-pour-les-validations-de-brevets-europeens-en-turquie", "answer" => "Oui, si le demandeur n'a pas de résidence ou de siège social en Turquie, vous devez nommer un conseil en brevets turc inscrit pour les validations de brevets européens en Turquie. De plus, même si vous remplissez les conditions de résidence et/ou de lieu d'affaires, nous vous conseillons néanmoins de travailler avec un conseil en brevets national pour faciliter les échanges avec l'office des brevets.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "La Turquie est-elle un État contractant à l'accord de Londres ?", "question_link" => "la-turquie-est-elle-un-etat-contractant-a-laccord-de-londres", "answer" => "Non, la Turquie n'est pas un État contractant à l'accord de Londres. Par conséquent, une traduction en turc de la description complète du brevet est requise.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "La traduction de la description est-elle requise pour les validations de brevets européens en Turquie ?", "question_link" => "la-traduction-de-la-description-est-elle-requise-pour-les-validations-de-brevets-europeens-en-turquie", "answer" => "Oui, le Turkpatent exige que la spécification complète, y compris les revendications, les dessins et la description, soit traduite en turc. Vous pouvez utiliser notre <a href='/validation-de-brevet-europeen-en-turquie'>outil de validation EP</a> pour obtenir un devis rapide sur les frais de traduction finaux à engager pour votre validation.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "Quel est le délai pour déposer la traduction d'une validation de brevet européen en Turquie ?", "question_link" => "quel-est-le-delai-pour-deposer-la-traduction-dune-validation-de-brevet-europeen-en-turquie", "answer" => "La traduction doit être déposée dans les trois mois suivant la date de publication de la mention de la délivrance dans le Bulletin européen des brevets. Une prolongation de trois mois moyennant le paiement d'un supplément est également possible.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "Est-il possible de faire une validation tardive d'un brevet européen ?", "question_link" => "est-il-possible-de-faire-une-validation-tardive-dun-brevet-europeen", "answer" => "Une prolongation de trois mois pour déposer la traduction est possible moyennant le paiement d'un supplément. Toutefois, l'option de déposer la traduction pendant cette prolongation de trois mois n'est possible que si les frais de publication et le supplément ont été payés <b>à l'avance</b>, dans le délai initial de trois mois à compter de la mention de délivrance. Si votre cas ne remplit pas ces conditions, il peut y avoir des cas particuliers où il est encore possible de valider votre brevet. Si vous avez besoin de plus d'informations à ce sujet, veuillez <a href='/contact?late-ep-application'>nous contacter</a>.", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array("title" => "Validation de brevet européen en Turquie", "slug" => "validation-de-brevet-europeen-en-turquie", "question" => "Combien coûte une validation d'un brevet européen en Turquie ?", "question_link" => "combien-coute-une-validation-dun-brevet-europeen-en-turquie", "answer" => "Les coûts de validation d'un brevet européen en Turquie comprennent les frais officiels, les honoraires du représentant et les frais de traduction. Les frais officiels pour le dépôt d'une validation de brevet européen peuvent varier considérablement chaque année et vous pouvez consulter les frais officiels les plus récents dans <a href='/validation-de-brevet-europeen-en-turquie/quels-sont-les-frais-officiels-pour-les-validations-de-brevets-europeens-en-turquie'>cette page</a>. <br> Le coût total d'une validation varie d'un brevet à l'autre. Vous pouvez utiliser notre outil de validation EP <a href='/validation-de-brevet-europeen-en-turquie'>pour obtenir un devis précis instantané pour la validation de votre brevet européen en Turquie.</a>", "type" => "Base de connaissances", "created_at" => NULL, "updated_at" => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => "Quels sont les frais officiels pour la validation d'un brevet européen en Turquie ?", 'question_link' => 'quels-sont-les-frais-officiels-pour-la-validation-dun-brevet-europeen-en-turquie', 'answer' => "Le montant des frais officiels s'élève à 8910,00 TRY en 2023 pour la publication d'une traduction de la spécification du brevet. Toutefois, pour une prolongation de trois mois en cas de dépôt tardif de la traduction, un supplément de 5040,00 TRY doit être payé à l'avance. <br> Vous pouvez utiliser notre <a href='/validation-de-brevet-europeen-en-turquie'>outil de validation de brevet européen</a> pour obtenir un calcul précis des frais officiels et des coûts totaux pour la validation de vos brevets européens en Turquie.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => 'Quand les frais officiels doivent-ils être payés ?', 'question_link' => 'quand-les-frais-officiels-doivent-ils-etre-payes', 'answer' => "Les frais officiels doivent être payés dans les trois mois suivant la date de publication de la mention de la délivrance dans le Bulletin des brevets européens. Si vous demandez une prolongation de trois mois pour un dépôt tardif, le supplément doit être payé à l'avance pendant la même période.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => 'Combien de temps faut-il pour valider un brevet européen en Turquie ?', 'question_link' => 'combien-de-temps-faut-il-pour-valider-un-brevet-europeen-en-turquie', 'answer' => "La validation d'un brevet européen en Turquie est généralement terminée en quelques jours. Cependant, le processus de traduction présente une certaine variabilité naturelle. Pour éviter des frais supplémentaires, il est conseillé de donner des instructions en temps voulu.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => "Est-ce que l'obtention d'un pouvoir de représentation est nécessaire pour valider un brevet européen en Turquie ?", 'question_link' => 'est-ce-que-lobtention-dun-pouvoir-de-representation-est-necessaire-pour-valider-un-brevet-europeen-en-turquie', 'answer' => "Non, l'obtention d'un pouvoir de représentation n'est pas nécessaire en Turquie pour la validation des brevets européens. Cependant, votre avocat pourrait préférer avoir un pouvoir de représentation signé de la part du demandeur en cas de besoins futurs.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => 'Est-il possible de déposer tardivement la traduction ?', 'question_link' => 'est-il-possible-de-deposer-tardivement-la-traduction', 'answer' => "Oui, une prolongation de trois mois est possible moyennant le paiement d'un supplément. Cependant, l'option de déposer la traduction pendant cette période de trois mois est disponible uniquement si les frais de publication et le supplément ont été payés <b>à l'avance</b>, dans la période initiale de trois mois à compter de la mention de délivrance.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => 'Est-il possible de corriger la traduction ?', 'question_link' => 'est-il-possible-de-corriger-la-traduction', 'answer' => "Oui, il est possible de corriger les traductions en Turquie. Une traduction corrigée de la spécification du brevet peut être déposée à tout moment après la validation du brevet européen. Vous pouvez consulter les frais officiels les plus récents pour le dépôt d'une traduction corrigée ici <a href='base-de-connaissances/validation-de-brevet-europeen-en-turquie/est-ce-que-lobtention-dun-pouvoir-de-representation-est-necessaire-pour-valider-un-brevet-europeen-en-turquie'></a>.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Validation de brevet européen en Turquie', 'slug' => 'validation-de-brevet-europeen-en-turquie', 'question' => "Quels sont les frais officiels à payer pour le dépôt d'une traduction corrigée ?", 'question_link' => "quels-sont-les-frais-officiels-a-payer-pour-le-depot-dune-traduction-corrige", 'answer' => "Si vous avez besoin d'une correction de traduction, les frais officiels pour la publication d'une traduction corrigée de la spécification du brevet s'élèvent à 2820,00 TRY pendant l'année 2023.", 'type' => 'Base de connaissances', 'created_at' => NULL, 'updated_at' => NULL),

                // german

                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist es möglich, ein europäisches Patent in der Türkei zu validieren?', 'question_link' => 'ist-es-moeglich-ein-europaeisches-patent-in-der-tuerkei-zu-validieren', 'answer' => 'Ja, die Türkei ist Vertragsstaat des Europäischen Patentübereinkommens, und die Validierung ist ein obligatorischer Schritt, um ein durchsetzbares Recht in der Türkei in Bezug auf ein europäisches Patent nach der Erteilung vor dem EPA zu besitzen. Es ist auch üblich, dass europäische Patentvalidierungen in der Türkei vorgenommen werden, sodass etwa ein Drittel aller Patenterteilungen in einem Jahr in der Türkei auf europäische Patentvalidierungen entfallen.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Muss für die europäische Patentvalidierung in der Türkei ein nationaler Berufungsvertreter ernannt werden?', 'question_link' => 'muss-fuer-die-europaeische-patentvalidierung-in-der-tuerkei-ein-nationaler-berufungsvertreter-ernannt-werden', 'answer' => 'Ja, wenn der Antragsteller keinen Wohnsitz oder Hauptsitz in der Türkei hat, muss für die europäische Patentvalidierung in der Türkei ein registrierter türkischer Patentanwalt ernannt werden. Selbst wenn Sie die Wohnsitz- und/oder Geschäftssitzanforderungen erfüllen, empfehlen wir Ihnen dennoch, mit einem nationalen Patentanwalt zusammenzuarbeiten, um bessere Kommunikationsmöglichkeiten mit dem Patentamt zu haben.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist die Türkei Vertragsstaat des Londoner Abkommens?', 'question_link' => 'ist-die-tuerkei-vertragsstaat-des-londoner-abkommens', 'answer' => 'Nein, die Türkei ist kein Vertragsstaat des Londoner Abkommens. Daher ist eine Übersetzung des vollständigen Patentspezifikationsdokuments ins Türkische erforderlich.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist für die europäische Patentvalidierung in der Türkei die Übersetzung der Beschreibung erforderlich?', 'question_link' => 'ist-fuer-die-europaeische-patentvalidierung-in-der-tuerkei-die-uebersetzung-der-beschreibung-erforderlich', 'answer' => 'Ja, das Türkische Patent- und Markenamt (Türkpatent) verlangt, dass die vollständige Spezifikation, einschließlich der Ansprüche, Zeichnungen und Beschreibung, ins Türkische übersetzt wird. Sie können unser <a href="/europaeische-patentvalidierung-in-der-tuerkei">EP Validierungstool</a> verwenden, um eine schnelle Kostenschätzung für die endgültigen Übersetzungskosten für Ihre Validierung zu erhalten.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Welcher Zeitraum gilt für die Einreichung der Übersetzung einer europäischen Patentvalidierung in der Türkei?', 'question_link' => 'welcher-zeitraum-gilt-fuer-die-einreichung-der-uebersetzung-einer-europaeischen-patentvalidierung-in-der-tuerkei', 'answer' => 'Die Übersetzung muss innerhalb von drei Monaten nach dem Datum der Veröffentlichung der Erteilung im Europäischen Patentblatt eingereicht werden. Eine Fristverlängerung von drei Monaten ist gegen Zahlung eines Zuschlags möglich.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist eine nachträgliche Validierung eines europäischen Patents möglich?', 'question_link' => 'ist-eine-nachtraegliche-validierung-eines-europaeischen-patents-moeglich', 'answer' => 'Eine dreimonatige Fristverlängerung für die Einreichung der Übersetzung ist gegen Zahlung eines Zuschlags möglich. Die Möglichkeit, die Übersetzung während dieser dreimonatigen Fristverlängerung einzureichen, besteht jedoch nur, wenn die Gebühr für die Veröffentlichung und der Zuschlag innerhalb des ersten Zeitraums von drei Monaten nach der Erteilung gezahlt wurden. Wenn Ihr Fall diese Bedingungen nicht erfüllt, kann es in einigen Ausnahmefällen dennoch möglich sein, Ihr Patent zu validieren. Wenn Sie weitere Informationen zu diesem Thema benötigen, kontaktieren Sie uns bitte unter <a href="/kontakt?=Nachtraegliche-EP-Anmeldung">Kontakt</a>.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Wie hoch sind die Kosten für die Validierung eines europäischen Patents in der Türkei?', 'question_link' => 'wie-hoch-sind-die-kosten-fuer-die-validierung-eines-europaeischen-patents-in-der-tuerkei', 'answer' => 'Die Kosten für die Validierung eines europäischen Patents in der Türkei setzen sich aus offiziellen Gebühren, Vertretergebühren und Übersetzungskosten zusammen. Die offiziellen Gebühren für die Einreichung einer europäischen Patentvalidierung können sich von Jahr zu Jahr erheblich ändern. Sie können die aktuellsten offiziellen Gebühren auf <a href="knowledge-base/europaeische-patentvalidierung-in-tuerkei/was-sind-die-offiziellen-gebuehren-fuer-europaeische-patentvalidierungen-in-der-tuerkei">dieser Seite</a> einsehen. Die Gesamtkosten für eine Validierung variieren je nach Patent. Verwenden Sie unser EP Validierungstool <a href="/europaeische-patentvalidierung-in-der-tuerkei">für einen sofortigen und genauen Kostenvoranschlag für Ihre europäische Patentvalidierung in der Türkei.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Was sind die offiziellen Gebühren für die Validierung europäischer Patente in der Türkei?', 'question_link' => 'was-sind-die-offiziellen-gebuhren-fur-die-validierung-europaischer-patente-in-der-turkei', 'answer' => 'Die offizielle Gebühr für die Veröffentlichung einer Übersetzung der Patentschrift beträgt 8910,00 TRY im Jahr 2023. Für eine dreimonatige Verlängerung der verspäteten Einreichung der Übersetzung ist im Voraus eine Zuschlagszahlung von 5040,00 TRY erforderlich. <br> Sie können unser <a href="/europaische-patentvalidierung-in-der-turkei">EP-Validierungstool</a> verwenden, um eine genaue Berechnung der offiziellen Gebühren und der Gesamtkosten für die Validierung Ihrer europäischen Patente in der Türkei zu erhalten.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Wann sind die offiziellen Gebühren fällig?', 'question_link' => 'wann-sind-die-offiziellen-gebuhren-fullig', 'answer' => 'Die offiziellen Gebühren sind innerhalb von drei Monaten nach dem Datum fällig, an dem die Bekanntmachung der Erteilung im Europäischen Patentblatt veröffentlicht wird. Wenn Sie eine dreimonatige Verlängerung für die verspätete Einreichung beantragen, muss der Zuschlag innerhalb desselben Zeitraums im Voraus gezahlt werden.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Wie lange dauert es, ein europäisches Patent in der Türkei zu validieren?', 'question_link' => 'wie-lange-dauert-es-ein-europaisches-patent-in-der-turkei-zu-validieren', 'answer' => 'Die Validierung eines europäischen Patents in der Türkei wird in der Regel innerhalb weniger Tage abgeschlossen. Der Übersetzungsprozess weist jedoch eine natürliche Variabilität auf. Um zusätzliche Zuschläge zu vermeiden, empfiehlt es sich, rechtzeitig Anweisungen zu erteilen.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist eine Vollmacht erforderlich, um ein europäisches Patent in der Türkei zu validieren?', 'question_link' => 'ist-eine-vollmacht-erforderlich-um-ein-europaisches-patent-in-der-turkei-zu-validieren', 'answer' => 'Nein, in der Türkei ist für die Validierung europäischer Patente keine Vollmacht erforderlich. Ihr Anwalt bevorzugt möglicherweise dennoch eine Vollmacht vom Antragsteller für zukünftige Anforderungen.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist eine verspätete Einreichung der Übersetzung möglich?', 'question_link' => 'ist-eine-verspatete-einreichung-der-ubersetzung-moglich', 'answer' => 'Ja, eine dreimonatige Verlängerung ist möglich, wenn ein Zuschlag gezahlt wird. Die Möglichkeit, die Übersetzung während dieser dreimonatigen Verlängerung einzureichen, besteht jedoch nur, wenn die Gebühr für die Veröffentlichung und der Zuschlag <b>im Voraus</b> innerhalb der anfänglichen Frist von drei Monaten nach der Erteilung bekannt gemacht wurden.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Ist die Korrektur der Übersetzung zulässig?', 'question_link' => 'ist-die-korrektur-der-ubersetzung-zulassig', 'answer' => 'Ja, Korrekturen von Übersetzungen sind in der Türkei zulässig. Eine korrigierte Übersetzung der Patentschrift kann jederzeit nach der Validierung des europäischen Patents eingereicht werden. Die aktuellsten offiziellen Gebühren für die Einreichung einer korrigierten Übersetzung finden Sie hier <a href=\'knowledge-base/europaische-patentvalidierung-in-der-turkei/ist-eine-vollmacht-erforderlich-um-ein-europaisches-patent-in-der-turkei-zu-validieren\'></a>.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => 'Europäische Patentvalidierung in der Türkei', 'slug' => 'europaische-patentvalidierung-in-der-turkei', 'question' => 'Welche offiziellen Gebühren fallen bei der Einreichung einer korrigierten Übersetzung an?', 'question_link' => 'welche-offiziellen-gebuhren-fallen-bei-der-einreichung-einer-korrigierten-ubersetzung-an', 'answer' => 'Wenn Sie eine Korrektur der Übersetzung benötigen, beträgt die offizielle Gebühr für die Veröffentlichung einer korrigierten Übersetzung der Patentschrift im Jahr 2023 2820,00 TRY.', 'type' => 'Wissensdatenbank', 'created_at' => NULL, 'updated_at' => NULL),


                //ko

                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허를 검증할 수 있을까요?', 'question_link' => 'turkiye에서-european-patent-validation-가능한가요', 'answer' => '네, 투르키는 유럽 특허 협약에 가입한 계약국이며, 유럽 특허의 검증은 EPO(European Patent Office)에서의 부여 후에 투르키에서 시행 가능한 권리를 갖기 위한 필수 단계입니다. 또한, EP 검증은 투르키에서 매우 흔하게 이루어지며, 투르키에서 연간 특허 부여의 약 3분의 1이 EP 검증입니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 위해 국가 전문 대리인을 지정해야 할까요?', 'question_link' => 'turkiye에서-european-patent-validations-을-위해-국가-전문-대리인-지정-필요한가요', 'answer' => '네, 투르키에 거주지나 사무소가 없는 경우, 투르키에서 유럽 특허 검증을 위해 등록된 투르키 특허 변리사를 지정해야 합니다. 또한, 거주지나 사업장 요건을 충족하더라도 특허청과의 원활한 의사소통을 위해 국내 특허 변리사와 협력하는 것이 좋습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키는 런던 협정의 계약국입니까?', 'question_link' => 'turkiye는-런던-협정의-계약국입니까', 'answer' => '아니요, 투르키는 런던 협정의 계약국이 아닙니다. 따라서, 완전한 특허 명세의 터키어 번역이 필요합니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 위해 설명서의 번역이 필요한가요?', 'question_link' => 'turkiye에서-european-patent-validations-을-위해-설명서의-번역-필요한가요', 'answer' => '네. Turkpatent는 클레임, 도면 및 설명을 모두 터키어로 번역해야 합니다. 특허 검증에 소요되는 최종 번역 비용에 대한 빠른 견적을 얻으려면 저희의 <a href="/european-patent-validation-in-turkey">EP Validation 도구</a>를 사용하실 수 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증의 번역을 제출하기 위한 기간은 어떻게 되나요?', 'question_link' => 'turkiye에서-european-patent-validation-의-번역-제출-기간', 'answer' => '번역은 유럽 특허 공보에 부여 공고가 발표된 날로부터 3개월 이내에 제출해야 합니다. 추가 수수료를 지불하여 3개월의 연장 기간을 받을 수도 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 지연해서 제출할 수 있나요?', 'question_link' => 'turkiye에서-european-patent-검증을-지연해서-제출-가능한가요', 'answer' => '수수료를 선불로 지불하고 3개월 내에 제출하는 경우에 한하여, 번역 제출을 위한 3개월 연장 기간을 이용할 수 있습니다. 그러나 이 조건을 충족하지 않는 경우에도 특허의 유효화에 관한 몇 가지 예외 사항이 있을 수 있습니다. 해당 사항에 대한 자세한 정보가 필요한 경우 <a href="/contact?=Late-EP-Application">문의</a>해 주시기 바랍니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증의 비용은 얼마인가요?', 'question_link' => 'turkiye에서-european-patent-validation-의-비용', 'answer' => '투르키에서 유럽 특허의 검증 비용은 공식 수수료, 대리인 수수료 및 번역 비용으로 구성됩니다. 유럽 특허 검증을 위한 공식 수수료는 매년 크게 변동할 수 있으며, 최신 공식 수수료는 <a href="knowledge-base/european-patent-validation-in-turkiye/what-are-the-official-fees-for-european-patent-validations-in-turkiye">이 페이지</a>에서 확인하실 수 있습니다. <br> 검증 비용은 특허마다 다를 수 있습니다. 투르키에서 유럽 특허의 검증 비용을 즉시 정확한 견적으로 알아보기 위해 저희의 EP Validation 도구 <a href="/european-patent-validation-in-turkiye">를 사용하실 수 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증','slug' => '유럽-특허-터키-유효성-검증','question' => '유럽 특허의 터키 유효성 검증에 대한 공식 수수료는 얼마입니까?','question_link' => 'what-are-the-official-fees-for-european-patent-validations-in-turkiye','answer' => '2023년에는 특허 명세서 번역의 게시를 위한 공식 수수료가 8910.00TRY입니다. 그러나 번역의 지연 제출을 위한 세 달 연장에는 5040.00TRY의 부가 요금을 미리 납부해야 합니다. <br> 유럽 특허의 터키 유효성 검증의 공식 수수료와 총 비용을 정확하게 계산하려면 저희 <a href="/european-patent-validation-in-turkiye">유효성 검증 도구</a>를 사용하실 수 있습니다.','type' => '지식 베이스','created_at' => NULL,'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증','slug' => '유럽-특허-터키-유효성-검증','question' => '공식 수수료는 언제 지불되어야 합니까?','question_link' => 'when-are-the-official-fees-due','answer' => '공식 수수료는 유럽 특허 공보에 공시된 승인 표시가 게시된 후 3개월 이내에 지불되어야 합니다. 세 달 연장을 요청하는 경우 부가 요금은 동일한 기간 내에 미리 지불되어야 합니다.','type' => '지식 베이스','created_at' => NULL,'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증','slug' => '유럽-특허-터키-유효성-검증','question' => '유럽 특허의 터키 유효성 검증은 얼마나 걸릴까요?','question_link' => 'how-long-does-it-take-to-validate-a-european-patent-in-turkiye','answer' => '유럽 특허의 터키 유효성 검증은 일반적으로 몇 일 안에 완료됩니다. 그러나 번역 과정에는 자연스러운 가변성이 내장되어 있습니다. 추가 부과 요금을 발생시키지 않으려면 제때 지시를 하는 것이 좋습니다.','type' => '지식 베이스','created_at' => NULL,'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증','slug' => '유럽-특허-터키-유효성-검증','question' => '유럽 특허의 터키 유효성 검증을 위해 위임장이 필요합니까?','question_link' => 'is-power-of-attorney-required-to-validate-a-european-patent-in-turkiye','answer' => '아니요, 터키에서는 유럽 특허의 유효성 검증을 위해 위임장이 필요하지 않습니다. 그러나 변호사는 향후 요구 사항을 위해 신청인으로부터 실행된 위임장을 갖는 것을 선호할 수 있습니다.','type' => '지식 베이스','created_at' => NULL,'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증','slug' => '유럽-특허-터키-유효성-검증','question' => '번역의 지연 제출은 가능한가요?','question_link' => 'is-late-filing-of-the-translation-possible','answer' => '네, 부가 요금을 지불함으로써 3개월 연장 기간이 제공됩니다. 그러나 발행 공고로부터 3개월 이내의 초기 기간에 게시 요금과 부가 요금을 <b>미리</b> 지불한 경우에만 번역을 이 기간 동안 제출할 수 있습니다.','type' => '지식 베이스','created_at' => NULL,'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '번역의 수정이 허용되나요?', 'question_link' => '번역의-수정이-허용되나요', 'answer' => '네, 터키에서는 번역의 수정을 허용합니다. 유효성 검증 후 특허 명세서의 수정된 번역은 언제든지 제출할 수 있습니다. 수정된 번역의 공식 수수료는 여기에서 확인하실 수 있습니다. <a href="지식-베이스/유럽-특허-터키-유효성-검증-위임장-필요합니까"></a>', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '수정된 번역을 제출하는 데 지불해야 하는 공식 수수료는 얼마입니까?', 'question_link' => '수정된-번역을-제출하는-데-지불해야-하는-공식-수수료는-얼마입니까', 'answer' => '번역의 수정이 필요한 경우, 2023년 동안 공식 수수료는 수정된 특허 명세서의 게시에 대한 2820.00TRY입니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),



                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허를 검증할 수 있을까요?', 'question_link' => 'turkiye에서-european-patent-validation-가능한가요', 'answer' => '네, 투르키는 유럽 특허 협약에 가입한 계약국이며, 유럽 특허의 검증은 EPO(European Patent Office)에서의 부여 후에 투르키에서 시행 가능한 권리를 갖기 위한 필수 단계입니다. 또한, EP 검증은 투르키에서 매우 흔하게 이루어지며, 투르키에서 연간 특허 부여의 약 3분의 1이 EP 검증입니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 위해 국가 전문 대리인을 지정해야 할까요?', 'question_link' => 'turkiye에서-european-patent-validations-을-위해-국가-전문-대리인-지정-필요한가요', 'answer' => '네, 투르키에 거주지나 사무소가 없는 경우, 투르키에서 유럽 특허 검증을 위해 등록된 투르키 특허 변리사를 지정해야 합니다. 또한, 거주지나 사업장 요건을 충족하더라도 특허청과의 원활한 의사소통을 위해 국내 특허 변리사와 협력하는 것이 좋습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키는 런던 협정의 계약국입니까?', 'question_link' => 'turkiye는-런던-협정의-계약국입니까', 'answer' => '아니요, 투르키는 런던 협정의 계약국이 아닙니다. 따라서, 완전한 특허 명세의 터키어 번역이 필요합니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 위해 설명서의 번역이 필요한가요?', 'question_link' => 'turkiye에서-european-patent-validations-을-위해-설명서의-번역-필요한가요', 'answer' => '네. Turkpatent는 클레임, 도면 및 설명을 모두 터키어로 번역해야 합니다. 특허 검증에 소요되는 최종 번역 비용에 대한 빠른 견적을 얻으려면 저희의 <a href="/european-patent-validation-in-turkey">EP Validation 도구</a>를 사용하실 수 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 위한 기간은 어떻게 되나요?', 'question_link' => 'turkiye에서-european-patent-validation-의-번역-제출-기간', 'answer' => '번역은 유럽 특허 공보에 부여 공고가 발표된 날로부터 3개월 이내에 제출해야 합니다. 추가 수수료를 지불하여 3개월의 연장 기간을 받을 수도 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증을 지연해서 제출할 수 있나요?', 'question_link' => 'turkiye에서-european-patent-검증을-지연해서-제출-가능한가요', 'answer' => '수수료를 선불로 지불하고 3개월 내에 제출하는 경우에 한하여, 번역 제출을 위한 3개월 연장 기간을 이용할 수 있습니다. 그러나 이 조건을 충족하지 않는 경우에도 특허의 유효화에 관한 몇 가지 예외 사항이 있을 수 있습니다. 해당 사항에 대한 자세한 정보가 필요한 경우 <a href="/contact?=Late-EP-Application">문의</a>해 주시기 바랍니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),
                array('title' => '유럽 특허 터키 유효성 검증', 'slug' => '유럽-특허-터키-유효성-검증', 'question' => '투르키에서 유럽 특허 검증의 비용은 얼마인가요?', 'question_link' => 'turkiye에서-european-patent-validation-의-비용', 'answer' => '투르키에서 유럽 특허의 검증 비용은 공식 수수료, 대리인 수수료 및 번역 비용으로 구성됩니다. 유럽 특허 검증을 위한 공식 수수료는 매년 크게 변동할 수 있으며, 최신 공식 수수료는 <a href="knowledge-base/european-patent-validation-in-turkiye/what-are-the-official-fees-for-european-patent-validations-in-turkiye">이 페이지</a>에서 확인하실 수 있습니다. <br> 검증 비용은 특허마다 다를 수 있습니다. 투르키에서 유럽 특허의 검증 비용을 즉시 정확한 견적으로 알아보기 위해 저희의 EP Validation 도구 <a href="/european-patent-validation-in-turkiye">를 사용하실 수 있습니다.', 'type' => '지식 베이스', 'created_at' => NULL, 'updated_at' => NULL),









            );

            DB::table('knowledge_base')->insert($knowledge_base);

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('knowledge_base', function (Blueprint $table) {
            //
        });
    }
};
