<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $faqs = array(
            array('title' => 'Patist IP Türkiye Nedir?', 'answer' => "Patist IP Türkiye, Türkiye'de patent koruması için başvuruda bulunmak isteyen patent firmaları, avukatlar veya mucitler için tasarlanmış otomatik bir Fikri Mülkiyet Hizmetleri aracıdır. Patist IP Türkiye ile ilgilenen taraflar, Türkiye'de yaygın olarak kullanılan bazı patent başvuru türleri için anında bir fiyat teklifi alabilirler.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Qu'est-ce que Patist IP Turquie?", 'answer' => "Patist IP Turquie est un outil de services de propriété intellectuelle automatisé conçu pour les cabinets de brevets, les avocats ou les inventeurs qui souhaitent déposer une demande de protection de brevet en Turquie. Avec Patist IP Turquie, les parties intéressées peuvent obtenir un devis instantané pour certains types de demandes de brevet courants en Turquie.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Cos'è Patist IP Turchia?", 'answer' => "Patist IP Turchia è uno strumento automatizzato di servizi di proprietà intellettuale progettato per studi di brevetti, avvocati o inventori interessati a presentare una domanda di protezione brevettuale in Turchia. Con Patist IP Turchia, le parti interessate sono in grado di ottenere un preventivo immediato per alcuni tipi comuni di domande di brevetto in Turchia.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Was ist Patist IP Türkei?", 'answer' => "Patist IP Türkei ist ein automatisiertes IP-Dienstleistungstool, das für Patentfirmen, Anwälte oder Erfinder entwickelt wurde, die eine Patentanmeldung in der Türkei beantragen möchten. Mit Patist IP Türkei können interessierte Parteien ein sofortiges Angebot für einige gängige Arten von Patentanmeldungen in der Türkei erhalten.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Qué es Patist IP Turquía?", 'answer' => "Patist IP Turquía es una herramienta automatizada de servicios de propiedad intelectual diseñada para empresas de patentes, abogados o inventores que deseen solicitar protección de patente en Turquía. Con Patist IP Turquía, las partes interesadas pueden obtener un presupuesto instantáneo para algunos tipos comunes de solicitudes de patente en Turquía.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "Patist IPトルコとは何ですか？", 'answer' => "Patist IPトルコは、トルコで特許保護の申請を希望する特許法事務所、弁護士、または発明者向けの自動化された知的財産サービスツールです。 Patist IPトルコを利用することで、関係者はトルコで一般的な特許申請のタイプに対して即座に見積もりを取得することができます。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),
            array('title' => "Patist IP 터키란 무엇인가요?", 'answer' => "Patist IP 터키는 특허 법률 사무소, 변호사 또는 발명가들이 터키에서 특허 보호를 신청하고자하는 자동화된 지적 재산 서비스 도구입니다. Patist IP 터키를 통해 관련 당사자들은 터키에서 일반적인 특허 신청 유형에 대한 즉각적인 견적을 받을 수 있습니다.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),


            array('title' => "Patist IP Türkiye'nin Amacı Nedir?", 'answer' => "Fikri Mülkiyet hizmetlerinin maliyeti, bir Fikri Mülkiyet stratejisi oluşturmak için önemli bir girdidir. Patist IP Türkiye, müşteriler için maliyet tahmini sürecini kolaylaştırır. <br><br> Geleneksel maliyet tahmini sürecinde, bir Fikri Mülkiyet temsilcisi, yerel yargı alanındaki güvenilir bir Fikri Mülkiyet firmasından bir teklif istemektedir. Yerel firma tarafından yapılan bazı ilk çalışmaların ardından teklif hazırlanır ve temsilciye gönderilir, ardından Fikri Mülkiyet sahibine iletilir. Bu süreç, doğru ve güncel maliyet tahminlerini sağlamakla birlikte, doğruluktan ödün vermeden daha iyi ve daha verimli bir maliyet tahmini sağlama yöntemi mevcuttur. <br><br> Patist IP Türkiye, Türkiye'deki patent başvuruları için anında, doğru ve şeffaf teklifler sunarak bu boşluğu doldurur. Patist IP Türkiye tarafından sunulan teklifler sadece doğru değil, aynı zamanda teknoloji sayesinde idari maliyetlerin ortadan kalkmasıyla daha düşük maliyetlere yol açmaktadır.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Pourquoi Patist IP Turquie?", 'answer' => "Le coût des services de propriété intellectuelle est une donnée importante pour la création d'une stratégie de propriété intellectuelle. Patist IP Turquie rend le processus d'estimation des coûts facile pour les clients. <br><br> Dans le processus traditionnel d'estimation des coûts, le représentant d'une entreprise de propriété intellectuelle demande à un cabinet de propriété intellectuelle de confiance dans la juridiction locale de fournir un devis. Après un travail initial effectué par le cabinet local, le devis est préparé et envoyé au représentant, qui à son tour le transmet au propriétaire de la propriété intellectuelle. Bien que ce processus garantisse des estimations de coûts précises et à jour, il existe une meilleure manière, plus efficace, de fournir des estimations de coûts sans compromis sur la précision. <br><br> Patist IP Turquie comble cette lacune en fournissant des devis instantanés, précis et transparents pour les demandes de brevets en Turquie. Les devis fournis par Patist IP Turquie sont non seulement précis, mais ils permettent également de réduire les coûts en éliminant les frais administratifs grâce à la technologie.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Perché Patist IP Turchia?", 'answer' => "Il costo dei servizi di proprietà intellettuale è un elemento importante per la creazione di una strategia di proprietà intellettuale. Patist IP Turchia rende il processo di stima dei costi semplice per i clienti. <br><br> Nel tradizionale processo di stima dei costi, il rappresentante di una società di proprietà intellettuale richiede a un affidabile studio di proprietà intellettuale nella giurisdizione locale di fornire un preventivo. Dopo alcuni lavori preliminari dello studio locale, il preventivo viene preparato e inviato al rappresentante, che a sua volta lo trasmette al proprietario della proprietà intellettuale. Sebbene questo processo garantisca stime di costi accurate e aggiornate, esiste un modo migliore e più efficiente per fornire stime di costi senza compromettere l'accuratezza. <br><br> Patist IP Turchia colma questa lacuna fornendo preventivi istantanei, precisi e trasparenti per le domande di brevetto in Turchia. I preventivi forniti da Patist IP Turchia sono non solo precisi, ma anche vantaggiosi in termini di costi grazie all'eliminazione degli oneri amministrativi tramite la tecnologia.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Warum Patist IP Türkei?", 'answer' => "Die Kosten für geistiges Eigentum sind eine wichtige Grundlage für die Entwicklung einer IP-Strategie. Patist IP Türkei vereinfacht den Prozess der Kostenschätzung für die Kunden. <br><br> Im herkömmlichen Prozess der Kostenschätzung bittet der Vertreter eines IP-Unternehmens eine vertrauenswürdige IP-Firma in der jeweiligen Gerichtsbarkeit um ein Angebot. Nach einigen Vorarbeiten des lokalen Unternehmens wird das Angebot erstellt und an den Vertreter geschickt, der es wiederum dem IP-Inhaber übergibt. Obwohl dieser Prozess genaue und aktuelle Kostenschätzungen gewährleistet, gibt es eine bessere und effizientere Möglichkeit, Kostenschätzungen ohne Kompromisse bei der Genauigkeit anzubieten. <br><br> Patist IP Türkei schließt diese Lücke, indem es sofortige, genaue und transparente Angebote für Patentanmeldungen in der Türkei bietet. Die von Patist IP Türkei bereitgestellten Angebote sind nicht nur genau, sondern führen auch zu niedrigeren Kosten aufgrund der Eliminierung von Verwaltungsaufwand durch Technologie.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Por qué Patist IP Turquía?", 'answer' => "El costo de los servicios de propiedad intelectual es un elemento importante para crear una estrategia de propiedad intelectual. Patist IP Turquía hace que el proceso de estimación de costos sea fácil para los clientes. <br><br> En el proceso tradicional de estimación de costos, el representante de una empresa de propiedad intelectual solicita a una firma de propiedad intelectual de confianza en la jurisdicción local que proporcione un presupuesto. Después de realizar algunas tareas iniciales por parte de la firma local, se prepara el presupuesto y se envía al representante, quien a su vez lo pasa al propietario de la propiedad intelectual. Si bien este proceso garantiza estimaciones de costos precisas y actualizadas, existe una forma mejor y más eficiente de proporcionar estimaciones de costos sin comprometer la precisión. <br><br> Patist IP Turquía cubre esta brecha al proporcionar presupuestos instantáneos, precisos y transparentes para las solicitudes de patentes en Turquía. Los presupuestos proporcionados por Patist IP Turquía no solo son precisos, sino que también resultan en menores costos debido a la eliminación de gastos administrativos con la tecnología.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "Patist IP Turkey의 이유는 무엇인가요?", 'answer' => "지적 재산(IP) 서비스의 비용은 IP 전략 수립에 중요한 요소입니다. Patist IP Turkey는 고객들을 위해 비용 산출 과정을 간편하게 만들어줍니다. <br> 기존의 비용 산출 과정에서는 IP 대표자가 현지 관할권 내 신뢰할 수 있는 IP 기업에 견적을 요청합니다. 현지 기업에서 초기 작업을 수행한 후 견적을 작성하여 대표자에게 보내고, 이를 다시 IP 소유자에게 전달합니다. 이 과정은 정확하고 최신의 비용 산출을 보장하지만, 정확성을 희생하지 않고 비용 산출을 더 나은 방식으로 제공할 수 있는 방법이 있습니다. <br> Patist IP Turkey는 터키 내 특허 출원에 대한 즉각적이고 정확하며 투명한 견적을 제공함으로써 이러한 공백을 메웁니다. Patist IP Turkey에서 제공하는 견적은 정확할 뿐만 아니라 기술을 통해 행정 오버헤드를 제거하여 비용을 절감시킵니다.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),
            array('title' => "なぜPatist IPトルコを利用するのですか？", 'answer' => "知的財産（IP）サービスの費用は、IP戦略の構築において重要な要素です。Patist IPトルコは、顧客にとって費用見積もりプロセスを簡単にします。 <br> 従来の費用見積もりプロセスでは、IP代理人が現地の信頼できるIP企業に見積もりを依頼します。現地企業による初期作業の後、見積もりが作成され代理人に送られ、IP所有者に伝えられます。このプロセスは正確で最新の費用見積もりを保証しますが、正確性を損なうことなく費用見積もりを提供するためのより良いかつ効率的な方法が存在します。 <br> Patist IPトルコは、トルコでの特許出願に対して瞬時で正確かつ透明な見積もりを提供することで、このギャップを埋めます。Patist IPトルコによる提供される見積もりは正確であり、技術による行政のオーバーヘッドの排除によりコストを削減することができます。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),


            array('title' => "Patist IP Turkey'nin avantajları nelerdir?", 'answer' => '<ul style="list-style-type: circle;margin: 0 0 3px 0; "> <li>Anlık: Patist IP Turkey, anlık teklifler sunar. Bu, sizin tarafınızda verimli ve sorunsuz karar alma imkanı sağlar.</li> <li>Doğru: Teklif, başvurunuz ve mevcut durumu temel alınarak verilir.</li> <li>Maliyet etkin: Otomasyon kullanımı, ek maliyet olmadan her zaman makul maliyetler.</li> <li>Şeffaf: Maliyet yapısı ve hizmet ücretlerimiz şeffaftır. Sunulan tekliflerde her maliyet kalemi açıkça belirtilir. Hiçbir gizli maliyet yoktur.</li> <li>Kalite Garantisi: Sağladığınız talimatlar, yerel yargı alanında on yıllık deneyime sahip yetenekli bir ekip tarafından işlenir. Operasyonlar ve kalite, Proust Patent tarafından desteklenir.</li> </ul>', 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Quels sont les avantages de Patist IP Turquie?", 'answer' => '<ul style="list-style-type: circle;margin: 0 0 3px 0; "> <li>Instantané : Patist IP Turquie fournit des devis instantanés. Cela permet une prise de décision efficace et fluide de votre côté.</li> <li>Précis : Le devis est établi en fonction de votre demande et de son état actuel.</li> <li>Économique : Utilisation de\'automatisation, pas de frais généraux, des coûts toujours raisonnables.</li> <li>Transparent : La structure des coûts et nos frais de service sont transparents. Chaque élément de coût est clairement indiqué dans les devis fournis. Aucun coût caché.</li> <li>Qualité garantie : Les instructions que vous fournissez sont traitées par une équipe talentueuse ayant des décennies d\'expérience dans la juridiction locale. Les opérations et la qualité sont soutenues par Proust Patent.</li> </ul>', 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr', 'slug' =>'FAQs' ),
            array('title' => "Quali sono i vantaggi di Patist IP Turchia?", 'answer' => '<ul style="list-style-type: circle;margin: 0 0 3px 0; "> <li>Istantaneo: Patist IP Turchia fornisce preventivi istantanei. Ciò consente una decisione efficiente e fluida da parte vostra.</li> <li>Preciso: Il preventivo viene fornito in base alla vostra domanda e al suo stato attuale.</li> <li>Costo efficace: Utilizzo dell\'automazione, nessun costo aggiuntivo, costi sempre ragionevoli.</li> <li>Trasparente: La struttura dei costi e le tariffe del nostro servizio sono trasparenti. Ogni voce di costo è chiaramente indicata nei preventivi forniti. Nessun costo nascosto.</li> <li>Qualità garantita: Le istruzioni che fornite vengono elaborate da un team talentuoso con decenni di esperienza nella giurisdizione locale. Le operazioni e la qualità sono supportate da Proust Patent.</li> </ul>', 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it', 'slug' =>'FAQs' ),
            array('title' => "Welche Vorteile bietet Patist IP Türkei?", 'answer' => "<ul style=\"list-style-type: circle;margin: 0 0 3px 0; \"> <li>Sofortig: Patist IP Türkei bietet sofortige Angebote. Dies ermöglicht effiziente und reibungslose Entscheidungsfindung auf Ihrer Seite.</li> <li>Genau: Das Angebot wird auf der Grundlage Ihrer Anwendung und ihres aktuellen Status abgegeben.</li> <li>Kosteneffektiv: Einsatz von Automatisierung, keine Overhead-Kosten, immer angemessene Kosten.</li> <li>Transparent: Die Kostenstruktur und unsere Servicegebühren sind transparent. Jeder Kostenpunkt wird in den bereitgestellten Angeboten deutlich aufgelistet. Keine versteckten Kosten.</li> <li>Qualitätsgarantie: Die von Ihnen bereitgestellten Anweisungen werden von einem talentierten Team mit jahrzehntelanger Erfahrung in der lokalen Gerichtsbarkeit bearbeitet. Die Betriebsabläufe und die Qualität werden von Proust Patent unterstützt.</li> </ul>", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de', 'slug' =>'FAQs' ),
            array('title' => "¿Cuáles son las ventajas de Patist IP Turquía?", 'answer' => "<ul style=\"list-style-type: circle;margin: 0 0 3px 0; \"> <li>Instantáneo: Patist IP Turquía proporciona cotizaciones instantáneas. Esto permite una toma de decisiones eficiente y fluida por su parte.</li> <li>Preciso: La cotización se realiza en función de su solicitud y su estado actual.</li> <li>Económico: Uso de automatización, sin gastos generales, costos siempre razonables.</li> <li>Transparente: La estructura de costos y las tarifas de nuestro servicio son transparentes. Cada ítem de costo se enumera claramente en las cotizaciones proporcionadas. Sin costos ocultos.</li> <li>Calidad garantizada: Las instrucciones que proporciona son procesadas por un equipo talentoso con décadas de experiencia en la jurisdicción local. Las operaciones y la calidad están respaldadas por Proust Patent.</li> </ul>", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es', 'slug' =>'FAQs' ),
            array('title' => "Patist IP Turkey의 장점은 무엇인가요?", 'answer' => "<ul style=\"list-style-type: circle;margin: 0 0 3px 0; \"> <li>즉시 제공: Patist IP Turkey는 즉각적인 견적을 제공합니다. 이를 통해 효율적이고 원활한 의사 결정이 가능합니다.</li> <li>정확성: 견적은 신청서와 현재 상태에 기반하여 제공됩니다.</li> <li>비용 효율적: 자동화의 활용, 부가 비용 없이 항상 합리적인 비용입니다.</li> <li>투명성: 비용 구조와 서비스 수수료가 투명하게 공개됩니다. 제공되는 견적에는 각 비용 항목이 명확히 나열됩니다. 숨겨진 비용은 없습니다.</li> <li>품질 보장: 제공하는 지침은 현지 관할권에서 수십 년 경험을 갖춘 역량 있는 팀에 의해 처리됩니다. 운영과 품질은 Proust Patent에서 보증됩니다.</li> </ul>", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko', 'slug' =>'FAQs' ),
            array('title' => "Patist IP Turkeyの利点は何ですか？", 'answer' => "<ul style=\"list-style-type: circle;margin: 0 0 3px 0; \"> <li>即時提供: Patist IP Turkeyは即座の見積もりを提供します。これにより、効率的でスムーズな意思決定が可能です。</li> <li>正確性: 見積もりは、申請内容と現在の状況に基づいて提供されます。</li> <li>費用効果: 自動化の活用、余分なオーバーヘッドのない常に合理的なコストです。</li> <li>透明性: コスト構造とサービス料金は透明性があります。提供される見積もりには、各コスト項目が明確にリストされています。隠れた費用は一切ありません。</li> <li>品質保証: 提供された指示は、地元の法執行機関で数十年の経験を持つ才能あるチームによって処理されます。運営と品質はProust Patentによって保証されています。</li> </ul>", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja', 'slug' =>'FAQs' ),


            array('title' => 'Patent İstanbul tamamen otomatik mi?', 'answer' => "Yazılımımız patent ofisleriyle entegre edilmiştir. Türkiye'de EP onaylama, PCT ulusal aşama girişleri ve yenilemeler için maliyet tahmini ve siparişler tamamen otomatik olarak gerçekleştirilir. <br><br> Sipariş alındıktan sonra, fikri mülkiyet işlemleri otomatik olarak gerçekleştirilmez, deneyimli paralel ve patent avukatlarımız tarafından yönetilir. Bu, bir tarafın Turkpatent olduğu işlemler için gereken bir prosedürdür ve daha fazla kalite güvencesi sağlar.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Patent Istanbul est-il entièrement automatisé?", 'answer' => "Notre logiciel est intégré aux offices des brevets. L'estimation des coûts et les commandes sont entièrement automatisées pour la validation EP, les entrées en phase nationale du PCT et les renouvellements en Turquie. <br><br> Une fois la commande reçue, les opérations de PI ne sont pas automatisées mais gérées par nos parajuristes et avocats en brevets expérimentés. Il s'agit d'une procédure nécessaire pour les opérations impliquant l'Office turc des brevets, ce qui garantit une assurance qualité supplémentaire.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Patent Istanbul è completamente automatizzato?", 'answer' => "Il nostro software è integrato con gli uffici brevetti. La stima dei costi e gli ordini sono completamente automatizzati per la convalida EP, le fasi nazionali del PCT e i rinnovi in Turchia. <br><br> Una volta ricevuto l'ordine, le operazioni di PI non sono automatizzate, ma gestite dai nostri paralegali ed avvocati specializzati in brevetti. Questa è una procedura necessaria per le operazioni in cui una delle parti coinvolte è l'Ufficio Brevetti turco e fornisce ulteriori garanzie di qualità.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Ist Patent Istanbul vollständig automatisiert?", 'answer' => "Unsere Software ist mit Patentämtern integriert. Die Kostenabschätzung und Bestellungen für die EP-Validierung, nationale PCT-Phaseneinträge und Verlängerungen in der Türkei erfolgen vollständig automatisiert. <br><br> Sobald die Bestellung eingegangen ist, werden die geistigen Eigentumsoperationen nicht automatisiert, sondern von unseren erfahrenen Paralegals und Patentanwälten bearbeitet. Dies ist ein erforderliches Verfahren für Operationen, bei denen eine Partei Turkpatent ist, und es bietet zusätzliche Qualitätssicherung.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Patent Istanbul está completamente automatizado?", 'answer' => "Nuestro software está integrado con las oficinas de patentes. La estimación de costos y los pedidos se realizan completamente de forma automatizada para la validación EP, las entradas en la fase nacional del PCT y las renovaciones en Turquía. <br><br> Una vez que se recibe el pedido, las operaciones de PI no son automatizadas, sino que son gestionadas por nuestros paralegales y abogados de patentes con experiencia. Este es un procedimiento requerido para las operaciones en las que una de las partes es Turkpatent, lo cual proporciona una mayor garantía de calidad.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "패턴트 이스탄불은 완전히 자동화되어 있습니까?", 'answer' => "저희 소프트웨어는 특허청과 통합되어 있습니다. EP 유효성 검증, PCT 국가 단계 진입 및 특허 갱신에 대한 비용 산출과 주문은 완전히 자동화됩니다. <br><br> 주문이 접수되면, 지적 재산 작업은 자동화되지 않고 경험있는 파라리거 및 특허 변호사가 처리합니다. 이는 한국 특허청이 관련된 작업에서 필요한 절차로, 품질 보증을 추가로 제공합니다.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),
            array('title' => "Patent Istanbulは完全に自動化されていますか？", 'answer' => "当社のソフトウェアは特許庁と連携しています。EPバリデーション、PCT国内段階のエントリー、トルコでの特許更新に関する見積もりと注文は完全に自動化されています。 <br><br> 注文が受け取られた後、知的財産業務は自動化されず、経験豊富なパラリーガルと特許弁護士が対応します。これはトルコ特許庁が関与するオペレーションに必要な手続きであり、品質保証をさらに提供します。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),



            array('title' => 'Patist IP Turkey tarafından hangi hizmetler sunulmaktadır?', 'answer' => "Patist IP Turkey, Türkiye'de patent hizmetleri sunmaktadır. Bunlar arasında Turkpatent başvuruları, Türkiye'de Avrupa Patent validasyonları, Türkiye'de PCT ulusal aşama girişleri, yenilemeler, görüşler, patent arama hizmetleri ve patent izleme hizmetleri bulunmaktadır. <br><br> Lütfen sağlanan hizmetler için özel sayfamızı inceleyiniz.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Quels services sont fournis par Patist IP Turquie?", 'answer' => "Patist IP Turquie propose des services de brevet en Turquie, comprenant les demandes Turkpatent, les validations de brevets européens en Turquie, les entrées de phase nationale PCT en Turquie, les renouvellements, les avis, les services de recherche de brevets et les services de surveillance de brevets. <br><br> Veuillez consulter notre page dédiée aux services proposés.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Quali servizi vengono forniti da Patist IP Turchia?", 'answer' => "Patist IP Turchia fornisce servizi di brevetti in Turchia, inclusi le domande Turkpatent, le validazioni di brevetti europei in Turchia, le fasi nazionali del PCT in Turchia, i rinnovi, le opinioni, i servizi di ricerca brevetti e i servizi di monitoraggio brevetti. <br><br> Si prega di consultare la nostra pagina dedicata ai servizi forniti.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Welche Dienstleistungen bietet Patist IP Türkei an?", 'answer' => "Patist IP Türkei bietet Patentdienstleistungen in der Türkei an, einschließlich Turkpatent-Anträge, Validierung europäischer Patente in der Türkei, PCT-Nationalphaseneinträge in der Türkei, Erneuerungen, Gutachten, Patentrecherchedienste und Patentüberwachungsdienste. <br><br> Bitte sehen Sie sich unsere dedizierte Seite für die angebotenen Dienstleistungen an.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Qué servicios ofrece Patist IP Turquía?", 'answer' => "Patist IP Turquía ofrece servicios de patentes en Turquía, que incluyen solicitudes de Turkpatent, validaciones de patentes europeas en Turquía, entradas de fase nacional del PCT en Turquía, renovaciones, opiniones, servicios de búsqueda de patentes y servicios de monitoreo de patentes. <br><br> Por favor, consulte nuestra página dedicada a los servicios ofrecidos.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "환자 IP 터키가 제공하는 서비스는 무엇인가요?", 'answer' => "Patist IP Turkey는 터키에서 특허 서비스를 제공합니다. 이에는 Turkpatent 신청, 터키에서의 유럽 특허 유효화, 터키에서의 PCT 국가 단계 진입, 갱신, 의견, 특허 검색 서비스 및 특허 모니터링 서비스가 포함됩니다. <br><br> 제공되는 서비스에 대한 자세한 내용은 전용 페이지를 참조해주세요.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),
            array('title' => "Patist IP Turkeyはどのようなサービスを提供していますか？", 'answer' => "Patist IP Turkeyは、トルコで特許サービスを提供しており、Turkpatent申請、トルコでの欧州特許の有効化、トルコでのPCT国内段階へのエントリー、更新、意見、特許検索サービス、特許監視サービスなどが含まれます。<br><br>提供されているサービスについては、専用ページをご覧ください。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),


            array('title' => 'Nasıl bir teklif alabilirim?', 'answer' => "Mümkün olduğunda teklifler otomatik olarak verilir. Hizmet sayfasına gidin, geçerli bir patent numarası varsa ilgili numarayı girin, hızlı adımları takip edin ve teklifinizi alın. Eğer aradığınız hizmet otomatik olarak sağlanmıyorsa, sadece iletişim sayfamızdan bir mesaj gönderin ve talebinizi belirtin, ekibimiz sizinle iletişime geçecektir.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Comment obtenir un devis?", 'answer' => "Les devis sont donnés automatiquement lorsque cela est possible. Rendez-vous simplement sur la page du service, entrez le numéro de brevet pertinent le cas échéant, suivez les étapes rapides et obtenez votre devis. Si le service que vous recherchez n'est pas automatisé, envoyez simplement un message depuis notre page de contact indiquant votre demande et notre équipe vous répondra.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Come ottenere un preventivo?", 'answer' => "I preventivi vengono forniti automaticamente quando possibile. Vai semplicemente alla pagina del servizio, inserisci il numero di brevetto pertinente, se applicabile, segui i passaggi rapidi e ottieni il tuo preventivo. Se il servizio che stai cercando non è automatizzato, invia semplicemente un messaggio dalla nostra pagina di contatto indicando la tua richiesta e il nostro team ti contatterà.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Wie erhalte ich ein Angebot?", 'answer' => "Angebote werden automatisch erstellt, wenn dies möglich ist. Gehen Sie einfach zur Service-Seite, geben Sie bei Bedarf die entsprechende Patentnummer ein, folgen Sie den schnellen Schritten und erhalten Sie Ihr Angebot. Wenn der von Ihnen gewünschte Service nicht automatisiert ist, senden Sie einfach eine Nachricht über unsere Kontaktseite mit Ihrer Anfrage und unser Team wird sich mit Ihnen in Verbindung setzen.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Cómo puedo obtener un presupuesto?", 'answer' => "Los presupuestos se brindan automáticamente cuando es posible. Simplemente ve a la página de servicios, ingresa el número de patente relevante si corresponde, sigue los pasos rápidos y obtén tu presupuesto. Si el servicio que estás buscando no está automatizado, simplemente envía un mensaje desde nuestra página de contacto indicando tu solicitud y nuestro equipo se pondrá en contacto contigo.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "견적을 어떻게 받을 수 있나요?", 'answer' => "가능한 경우 견적은 자동으로 제공됩니다. 서비스 페이지로 이동하여 해당하는 특허 번호를 입력하고 빠른 단계를 따라 견적을 받으세요. 자동화되지 않은 서비스인 경우, 문의 페이지에서 요청 내용을 기재한 메시지를 보내주시면 저희 팀이 연락드릴 것입니다.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),
            array('title' => "見積もりはどのように取得できますか？", 'answer' => "可能な場合、見積もりは自動的に提供されます。サービスページにアクセスし、該当する特許番号があれば入力し、ステップに従って簡単に見積もりを取得してください。自動化されていないサービスの場合は、お問い合わせページから要望を記載したメッセージを送信していただければ、弊社のチームがご連絡いたします。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),


            array('title' => 'Talimatlarımı kim yürütüyor?', 'answer' => "Patist IP Türkiye, sorunsuz bir fiyatlandırma deneyimi sunmak için özel bir otomasyon ekibine sahiptir. Sipariş verildikten sonra, tüm Fikri Mülkiyet işlemleri, Proust Patent'te deneyimli paralegal ve patent avukatları tarafından yürütülmektedir. Lütfen IP ekibi hakkında daha fazla bilgi için özel sayfalarımıza göz atın.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'tr','slug' =>'FAQs'),
            array('title' => "Qui traite mes instructions ?", 'answer' => "Patist IP Turkey dispose d'une équipe d'automatisation dédiée pour vous offrir une expérience de devis fluide. Une fois la commande passée, toutes les opérations de PI sont gérées par des parajuristes expérimentés et des avocats spécialisés en brevets chez Proust Patent. Veuillez consulter nos pages dédiées pour plus d'informations sur l'équipe de PI.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'fr','slug' =>'FAQs'),
            array('title' => "Chi sta gestendo le mie istruzioni?", 'answer' => "Patist IP Turkey dispone di un team di automazione dedicato per fornire un'esperienza di preventivo senza intoppi. Una volta effettuato l'ordine, tutte le operazioni relative alla proprietà intellettuale sono gestite da paralegali esperti e avvocati specializzati in brevetti presso Proust Patent. Si prega di consultare le nostre pagine dedicate per ulteriori informazioni sul team di proprietà intellettuale.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'it','slug' =>'FAQs'),
            array('title' => "Wer bearbeitet meine Anweisungen?", 'answer' => "Patist IP Turkey verfügt über ein spezialisiertes Automatisierungsteam, um Ihnen ein reibungsloses Angebotserlebnis zu bieten. Sobald die Bestellung aufgegeben wurde, werden alle geistigen Eigentumsrechte von erfahrenen Paralegals und Patentanwälten bei Proust Patent bearbeitet. Bitte besuchen Sie unsere speziellen Seiten für weitere Informationen zum IP-Team.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'de','slug' =>'FAQs'),
            array('title' => "¿Quién está llevando a cabo mis instrucciones?", 'answer' => "Patist IP Turkey cuenta con un equipo de automatización dedicado para brindarle una experiencia fluida de cotización. Una vez realizada la orden, todas las operaciones de propiedad intelectual son gestionadas por paralegales y abogados de patentes con experiencia en Proust Patent. Por favor, consulte nuestras páginas dedicadas para obtener más información sobre el equipo de PI.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'es','slug' =>'FAQs'),
            array('title' => "내 지시를 처리하는 사람은 누구인가요?", 'answer' => "Patist IP Turkey는 원활한 견적 제공을 위해 전용 자동화 팀을 보유하고 있습니다. 주문이 접수되면 모든 지식재산권 작업은 Proust Patent의 경험 많은 패러리걸과 특허 변호사들이 처리합니다. IP 팀에 대한 자세한 정보는 전용 페이지를 참조해주세요.", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ko','slug' =>'FAQs'),
            array('title' => "私の指示を担当しているのは誰ですか？", 'answer' => "Patist IP Turkeyは、スムーズな見積もり体験を提供するために専用の自動化チームを備えています。注文が確定されると、すべての知的財産権手続きはProust Patentの経験豊富なパラリーガルと特許弁護士が担当します。IPチームの詳細については、専用のページをご覧ください。", 'created_at' => NULL, 'updated_at' => NULL, 'type' => 'Frequently asked questions', 'language' =>'ja','slug' =>'FAQs'),



        );

        DB::table('faqs')->insert($faqs);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
};
